feat: Se agrega que verifique el quality gate

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -55,7 +55,12 @@ jobs:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       
       - name: Check SonarCloud Quality Gate
-        uses: sonarsource/sonarcloud-quality-gate-action@master
+        run: |
+          SONAR_STATUS=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=TobiasMaciel_TrabajoCI" | jq -r '.projectStatus.status')
+          if [ "$SONAR_STATUS" != "OK" ]; then
+            echo "Quality gate failed: $SONAR_STATUS"
+            exit 1
+          fi
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 
