Prueba

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -29,6 +29,18 @@ jobs:
 
       - name: Correr linter de HTML  
         run: npm run lint:html
+      
+      - name: Desplegar en Render
+        run: |
+          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST "https://api.render.com/deploy/srv-cpfne37109ks73bnsccg?key=jnQgfSOiqgI")
+          if [ $response -eq 200 ]; then
+            echo "Deployment successful"
+            curl -X POST -H 'Content-type: application/json' --data '{"channel":"general","text":"Deploy exitoso."}' https://slack.com/api/chat.postMessage?token=$SLACK_TOKEN
+          else
+            echo "Deployment failed with HTTP status code $response"
+            curl -X POST -H 'Content-type: application/json' --data '{"channel":"general","text":"¡Ha fallado el Deploy!"}' https://slack.com/api/chat.postMessage?token=$SLACK_TOKEN
+            exit 1
+          fi
 
   test:
     name: Se ejecutan los test
