feat: Se agrega que espere que deploye correctamente antes del tes de Cypress

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -89,17 +89,34 @@ jobs:
     needs: test
     if: success()
     steps:
-      - name: Desplegar en Render
+      - name: Iniciar despliegue
         run: |
           response=$(curl -s -o /dev/null -w "%{http_code}" -X POST "https://api.render.com/deploy/srv-cpfne37109ks73bnsccg?key=jnQgfSOiqgI")
           if [ $response -eq 200 ]; then
             echo "Deployment successful"
-            curl -X POST -H 'Content-type: application/json' --data '{"text":"Deploy exitoso."}' "$SLACK_WEBHOOK_DEPLOYS"
+            curl -X POST -H 'Content-type: application/json' --data '{"text":"Deploy iniciado correctamente."}' "$SLACK_WEBHOOK_DEPLOYS"
           else
             echo "Deployment failed with HTTP status code $response"
             curl -X POST -H 'Content-type: application/json' --data '{"text":"¡Ha fallado el Deploy!"}' "$SLACK_WEBHOOK_DEPLOYS"
             exit 1
           fi
+      - name: Despliegue en proceso
+        run:  |
+          deploy_status="pending"
+          while [ "$deploy_status" != "live" ]; do
+            response=$(curl -s -H "Authorization: Bearer $RENDER_API_KEY" "https://api.render.com/v1/services/srv-cpfne37109ks73bnsccg?key=jnQgfSOiqgI/deploys")
+            echo "Render API response: $response"
+            deploy_status=$(echo $response | jq -r '.[0].deploy.status') 
+            echo "Current deploy status: $deploy_status"
+            if [ "$deploy_status" == "failed" ]; then
+              echo "Deployment failed."
+              curl -X POST -H 'Content-type: application/json' --data '{"text":"¡Ha fallado el Deploy!"}' "$SLACK_WEBHOOK_DEPLOYS"
+              exit 1
+            fi
+            sleep 10
+          done
+          curl -X POST -H 'Content-type: application/json' --data '{"text":"Deploy exitoso."}' "$SLACK_WEBHOOK_DEPLOYS"
+          echo "Deployment completed successfully."
         env:
           SLACK_WEBHOOK_DEPLOYS: ${{ secrets.SLACK_WEBHOOK_DEPLOYS }}
 
